spring.application.name=bank-management

# Railway MySQL Configuration
spring.datasource.url=${jdbc:mysql://mainline.proxy.rlwy.net:32443/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${root}
spring.datasource.password=${yafgKHxOJKepHiGAkXiZFWnoCSlCnxFG}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}